### ISSUE TITLE
ENV's generated by tox-docker aren't accessible in the command section

### ISSUE THREAD

**Issue by BenStuart** [tox-dev/tox-docker#46] opened 2019-12-20 04:35 UTC
https://github.com/tox-dev/tox/issues/1487

**Comment by dcrosta** [comment] 2020-04-19 23:19
@BenStuart do you have a concise description of the problem? The thread linked above wanders quite a bit, and I'm not certain what behavior you expect to have or want to see changed...

**Comment by dcrosta** [comment] 2020-06-02 17:51
Duplicate of #55

**Closed by dcrosta** 2020-06-02 17:51 UTC
Labels: need-more-info
