### ISSUE TITLE
Regression in checking if the socket is open

### ISSUE THREAD

**Issue by thedrow** [tox-dev/tox-docker#39] opened 2019-06-10 15:11 UTC
On versions higher than 1.2.1 I'm getting the following exception:

```
Never got answer on port 5671/tcp from rabbitmq
```
See [build log](https://travis-ci.org/celery/py-amqp/jobs/543705784#L444) for details.

However, the build used to pass and we haven't changed anything.
Therefore, there must be a regression somewhere.

The build executes and passes when I pin tox-docker to 1.2.1.

**Comment by thedrow** [comment] 2019-06-10 15:30
Ignore the Windows build.

See https://travis-ci.org/celery/py-amqp/builds/543779240.

**Comment by dcrosta** [comment] 2019-06-10 23:45
Looks like the issue is with how Rabbit binds port 5672:

```
dcrosta@springtail:~/src/tox-docker ± docker run -P -d rabbitmq:alpine
3e64e6c3ef5d4fe7c0bbaa3958a5ac4837514dd5aec023dc85cd19464992e44a
dcrosta@springtail:~/src/tox-docker ± docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                             NAMES
3e64e6c3ef5d        rabbitmq:alpine     "docker-entrypoint.s…"   3 seconds ago       Up 2 seconds        0.0.0.0:32949->4369/tcp, 0.0.0.0:32948->5671/tcp, 0.0.0.0:32947->5672/tcp, 0.0.0.0:32946->25672/tcp   frosty_sammet
dcrosta@springtail:~/src/tox-docker ± docker inspect 3e64e6c3ef5d | grep -i gateway
            "Gateway": "172.17.0.1",
            "IPv6Gateway": "",
                    "Gateway": "172.17.0.1",
                    "IPv6Gateway": "",
dcrosta@springtail:~/src/tox-docker ± python
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> def connect_to(ip, port):
...     s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
...     s.settimeout(0.1)
...     s.connect((ip, port))
...

# rabbit port 4369
>>> connect_to("127.0.0.1", 32949)
>>> connect_to("0.0.0.0", 32949)
>>> connect_to("172.17.0.1", 32949)

# rabbit port 5671
>>> connect_to("127.0.0.1", 32948)
>>> connect_to("0.0.0.0", 32948)
>>> connect_to("172.17.0.1", 32948)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in connect_to
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused

# rabbit port 5672
>>> connect_to("127.0.0.1", 32947)
>>> connect_to("0.0.0.0", 32947)
>>> connect_to("172.17.0.1", 32947)

# rabbit port 25672
>>> connect_to("127.0.0.1", 32946)
>>> connect_to("0.0.0.0", 32946)
>>> connect_to("172.17.0.1", 32946)
>>>
```

I'm guessing this has something to do with how the bridge network interacts with how RabbitMQ opens the port in question, maybe an IPv4 vs. IPv6 thing. I think the easiest solution is to let you specify a `gateway_ip` in `tox.ini`, but I want to let this bake for a few days in case some more correct/less manual idea comes up from someone who understands Rabbit and/or Docker better than I do.

**Comment by thedrow** [comment] 2019-06-11 08:39
What has changed since 1.2.1?

**Comment by dcrosta** [comment] 2019-06-11 13:13
Ah, sorry — 1.3 started using the Gateway instead of always 0.0.0.0, which fixed some use cases (are #19). It looks like this broke some cases, too, unfortunately.

**Comment by dcrosta** [comment] 2019-06-11 13:26
Hm, in reading some more it looks like that was probably a mistaken use of the gateway, which only happens to work in some cases. 

The right approach seems to be to add an option to use the gateway, letting the user choose. 

I’m still confused about what RabbitMQ is doing that’s causing problems here though.

**Comment by thenewguy** [comment] 2019-11-09 22:02
I just encountered this.  Any tips on how to get this going?

**Comment by dcrosta** [comment] 2020-06-08 22:20
Closing this, as tox-docker 2.x will no longer do the port-test "health check". The correct solution is to configure a health check command that returns a successful (==0) status when rabbit is up and ready for connections, and some other status until then, or use https://hub.docker.com/r/healthcheck/rabbitmq which has the healthcheck configured in to its Dockerfile)

**Closed by dcrosta** 2020-06-08 22:20 UTC
